[licenses]
allow = ["MIT", "Apache-2.0"]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/estifie/est-core"]
